site_name: "Cambria Labs"
site_description: 'Product Lab | Makerspace | Entrepreneur Incubator'
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: deep purple
  font:
    text: 'Noto Sans JP' # 'Inter', 'Karla', 'Noto Sans JP', 'Montserrat', 'Open Sans'
    code: 'Roboto Mono' # 'Oxygen Mono', 'Fira Code', 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.tabs.sticky

# Enable Tags
# ISSUE: Whenever enabled, site search is disabled
# plugins:
#  - tags:
#      tags_file: topics.md 
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cambria-labs/site_www.cambria-labs.com
  generator: false



nav:
- 'About': 
  - 'About Cambria': about.md
  - 'Team': index.md
  - 'Our Approach': index.md
  - 'Locations': 
    - Austin: "index.md"
    - Medellin: "index.md"
- 'Services': services.md
- 'Clients': index.md
- 'Partners': index.md
- 'Events': index.md
- 'Blog': index.md
- 'Docs': index.md
- 'Tools': index.md
- 'Contact': index.md

