site_name: "Cambria Labs"
site_description: 'Product Lab | Makerspace | Entrepreneur Incubator'
extra_css:
  - css/custom.css
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: deep purple
  font:
    text: 'Noto Sans JP' # 'Inter', 'Karla', 'Noto Sans JP', 'Montserrat', 'Open Sans'
    code: 'Roboto Mono' # 'Oxygen Mono', 'Fira Code', 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - toc:
      title: Table of Contents

# Enable Tags
# ISSUE: Whenever enabled, site search is disabled
# plugins:
#  - tags:
#      tags_file: topics.md 
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cambria-labs/site_www.cambria-labs.com
  generator: false



nav:
  - 'About': 
    - 'About Cambria': about/about-cambria-labs.md
    - 'Team': index.md
    - 'Our Approach': operations/processes/product-development/product-development-process.md
    - 'Locations': 
      - Austin: "index.md"
      - Medellin: "index.md"
  - 'Services': services.md
  - 'Clients': index.md
  - 'Partners': index.md
  - 'Events': index.md
  - 'Blog': index.md
  - 'Docs': 
    - documentation/index.md
    - 'Product Manager Playbook': "documentation/pm_playbook.md"
  - 'Tools': index.md
  - 'Contact': index.md

